name: CI

on:
  pull_request:
    branches:
    - master
    paths-ignore:
    - '.github/**'
  push:
    branches:
    - update/*

jobs:
  build:
    timeout-minutes: 0
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-10.14]

    steps:
    - uses: actions/checkout@v1
    - name: bootstrap MacPorts
      run: . _ci/bootstrap.sh
    - name: Build
      run: |
        unset CC && source /opt/local/share/macports/setupenv.bash
        export PATH="/opt/mports/bin:${PWD}/../mpbb:$PATH" && hash -r
        sudo env PASTE_URL="$PASTE_URL" ./runner
